---
- name: Installing Mongodb
  hosts: mongodb
  become: true

  tasks:
    - name: Add mongodb repo
      ansible.builtin.template:
        src: files/mongodb-org-7.0.repo.j2
        dest: /etc/yum.repos.d/mongodb-org-7.0.repo
        mode: "0644"

    - name: Install mongodb
      ansible.builtin.dnf:
        name: mongodb-org
        state: present

    - name: Enable and start MongoDB service
      ansible.builtin.service:
        name: mongod
        state: started
        enabled: true
